/**
 * Stage - single unit of work in a workflow
 */
export interface Stage {
  id: string;
  agent: string;  // Agent ARN
  depends_on: string[];  // Stage IDs
  description: string;
  input: Record<string, InputValue>;
  output: StageOutput;
  execution: StageExecution;
  conditions: Condition[];
  metrics: string[];
}

export type InputValue =
  | string
  | { from: string }
  | { template: string };

export interface StageOutput {
  artifacts: ArtifactRef[];
}

export interface ArtifactRef {
  name: string;
  path_template: string;
  content_type?: string;
}

export interface StageExecution {
  mode: 'sequential' | 'parallel' | 'batch';
  batch_size?: number;
  retry: RetryConfig;
}

export interface RetryConfig {
  max_attempts: number;
  backoff_ms: number;
}

export interface Condition {
  when: string;
  operator: 'equals' | 'not_equals' | 'in' | 'not_in' | 'greater_than' | 'less_than';
  value: unknown;
}

/**
 * Agent definition within a workflow
 */
export interface AgentDefinition {
  name: string;  // ARN
  description: string;
  model: string;
  skills: string[];  // Skill ARNs
  tools: string[];  // Tool ARNs
  prompts: string[];  // Prompt ARNs
  timeout_ms?: number;
}

/**
 * Skill reference in workflow
 */
export interface SkillReference {
  source: string;  // ARN
  triggers: string[];
  compact_rules: boolean;
}

/**
 * Metrics configuration
 */
export interface MetricsConfig {
  streaming: boolean;
  interval_ms: number;
  channels: string[];
}

/**
 * Execution configuration
 */
export interface ExecutionConfig {
  mode: 'sequential' | 'parallel';
  stop_on_error: boolean;
}

/**
 * Workflow - top-level definition
 */
export interface Workflow {
  arn: string;
  name: string;
  version: string;
  description: string;
  agents: Record<string, AgentDefinition>;
  skills: Record<string, SkillReference>;
  stages: Stage[];
  execution: ExecutionConfig;
  metrics: MetricsConfig;
}

/**
 * Execution plan generated by WorkflowPlanner
 */
export interface ExecutionStep {
  step_id: string;
  stage_id: string;
  agent_arn: string;
  description: string;
  input_contracts: InputContract[];
  output_contract: OutputContract;
  depends_on: string[];
  retry_config: RetryStepConfig;
  conditions: ConditionSummary[];
}

export interface InputContract {
  name: string;
  source: InputSource;
  description: string;
}

export type InputSource =
  | { Static: string }
  | { StageOutput: { stage_id: string; output_name: string } }
  | { Variable: { name: string } }
  | { Template: { template: string } };

export interface OutputContract {
  artifacts: ArtifactContract[];
  result_field: string;
}

export interface ArtifactContract {
  name: string;
  path_template: string;
  content_type?: string;
}

export interface RetryStepConfig {
  max_attempts: number;
  backoff_ms: number;
}

export interface ConditionSummary {
  expression: string;
  operator: string;
  value: string;
}

export interface ExecutionPlan {
  workflow_arn: string;
  workflow_name: string;
  execution_order: ExecutionStep[];
  parallel_groups: string[][];
  total_steps: number;
  estimated_duration_ms?: number;
  input_variables: string[];
}
